import sys

with open(sys.argv[1],'r') as fp:
    for line in fp:
        if line.startswith('#'):continue
        line_temp = line.strip().split('\t')
        start = str(int(line_temp[1])-1000)
        end   = str(int())
        infos = line_temp[-3].split(';')
        
        

'''
BND
DEL
INS
INV
SPLIT

AGCACCATGTGACTCTCACCCCACCCTCCCTGTAGTCACACTATAAAAGCACCATGTGACTCTCACCCCACCCTCCCTGTGGTCACACTGTAAGAGCACCATGTGACTCTCACCCCACCCTCCCTGTAGTCACACTGTAAGAGCACCATGTGACTCTCACCCCACCCTCCCTGTAGTCATCCTGTAAGAGTACCAT
GTGACTCTCACCCCACCCTCCCTGTAGTCATATGGTAAAAGTACCATAATGGTCCAGTGAAGCAGCCACTCTGCAGCATGAAATCCCACAGGCACACATCATGATAAACAGCAGGTGATGCCTGCTCCATTGTGGTGCCATGGCATGCCATGGGTTTAATGATTACCCATGGGTTTAATGATTACCTAAGGCTTCCAAA
TTCAGCCTTGCATTTAAGACCTAGGATATGACCAGACTGATTCCAGAATCCCATCTTTGAGGGTCTATTTCCTGGGCTGGAACTACCTCTGGTACTGAATGGTATAATGGCCGGGAATCAATCAGAGAAACAAAACCTACACAGGCATTCAACAGATGGAATTTAATACAGGGAATTTTTTACAATGG    C     .
        PASS    IMPRECISE;SVTYPE=DEL;END=218281372;SVLEN=-3323;SVANN=TANDEM     GT:AD:DP        0/1:10,7:17
chr1_RagTag     218279960       pbsv.INS.35     T       TCTGTAAGAGCACCATGTGACTCTCACCCCACCCTCCCTGTAGTCATGCTGTAAGAGCACCATGTGACTCTCACCCCACCCTCCCTGTGGTCACACTGTAAGAGCACCATGTGACTCTCACCCCCACCCTCCCTGTAGTCACA
CTGTAAGAGCACCATGTGACTCTCGCCCCACCCTCCCTGTAGTCACACTGTAAGAGCACCATGTGACTCTCGCCCCACCCTCCCTGTAGTCACACTGTAAGAGCACCATGTGACTCTCACCCCACCCTCCCTGTAGTCACACTGTAAGAGCACCATGTGACTCTCACCCCACCCTCCCTGTAGTCACACTGTAAGAGCA
CCATGTGACTCTCACCCCACCCTCCCTGTAGTCATGCTGTAAGAGCACCATGTGACTCTCACCCCACCCTCCCTGTAGTCATGCTGTAAGAGCACCATGTGACTCTCACCCCACCCTCCCTGTAGTCACACTGTAAGAGCACCATGTGACTCTCACCCCACCCTCCCTGTAGTCACACTGTAAGAGCACCATGTGACTC
TCGCCCCACCCTCCCTGTAGTCACACTGTAAGAGCACCATGTGACTCTCACCCCACCCTCCCTGTAGTCACACTGTAAGAGCACCATGTGACTCTCACCCCACCCTCCCTGTAGTCACACTTAAAGCACCATGTGACTCTCACCCCCCCT  .       PASS    IMPRECISE;SVTYPE=INS;END=218279
960;SVLEN=690;SVANN=TANDEM      GT:AD:DP        0/1:10,7:17
chr1_RagTag     218904574       pbsv.INS.36     G       GCACACACCCCATCTGTGAGAGCACCCTCTGTGCCTGCACACACGCCCCACCTGTGAGAGCACACTCTGTGCCTGCACACATGCCCCACCTGTGAGAGCACGCTCTGTGCCTGCACACACACACCCCACCTGTGAGAGCCGCT
CTGTGCCTGCACACACACCCCACCTGTGAGAGCTCCTCTGTGCCTGCACACACACCCCACCTGTGAGAGCACCCTCTGTGCCTGCACACACGCCCCCACCTGTGAGAGCACGCTCTGTGCCTGCACACATGCCCCACCTGACAGCACCCTGTGCCTGCACACACACACCCCACCTGTGAGAGCTCGCTCTGTGCCTGCA
CACATGCCCCACCTGTGAGAGCACGCTCTGTGCCTGCACACACCACACCCCCACCTGTGCCTGCACACACACACCCCACCTGTGAGAGCCCTCTGTGCCTGCACACATGCCCCACCTGTGAGAGCCCTCTGTGCCTGCACACACACCCCC  .       PASS    IMPRECISE;SVTYPE=INS;END=218904
574;SVLEN=491;SVANN=TANDEM      GT:AD:DP        0/1:10,3:13
chr1_RagTag     219591949       pbsv.DEL.37     ATTTAGTATATACTTAAAAACACCAGATCCAGAAGGTTTTAGAGGGGAATTCTGTCAACTTTCCAGGAATAGAGCGTCGTGTATTTATAGGAACTCTTACAAAGACTAGAAAGGAATACATTTGGTCTCCAAACCCTTAAACTGGCCTACT
GTAACTTCAGTAACAGAAGAAAGCACAGATGCTAAAACTCTATGCAAAAATATTCGTAATCAATTCAGTAATCAATTAGTAATTATGTATGTTTTATCCAAGGAATGGAAGAGTGGAATACCCATGAAAAATATATAATATTCAGTCACCAAATTCACTTATTAAAGGAGAAAAATCTTATAATTAACATATGCAAAAA
AGCATTCCATAAAAGCTAATATTTATTAATTATTTTTTAACTTTCTTAACCCAGTACATTTAGTCCATAAAACCCCAGGACATTTAGTCCATAAAACCCCAGGACATTTAGTCCATAAAACCCCAGGACATTTAGTCCATAAAACCCCAGGACATTTA
'''
